apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
  	path('', views.Home_Noticias_clase.as_view(), name="h_noticias"),
]

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name ='inicio'),
    path('contacto', views.Contacto, name ='contacto'),

    #APP NOTICIAS
    path('noticias/', include('apps.noticias.urls')),
]

apps/noticias/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
	nombre = models.CharField(max_length = 100)

class Noticia(models.Model):

	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	titulo = models.CharField(max_length = 250)
	contenido = models.TextField()
	imagen = models. ImageField(upload_to = 'noticias')
	categoria = models.ForeignKey(Categoria, on_delete= models.CASCADE)


	def __str__(self):
		return self.titulo

apps/noticias/views.py
from django.shortcuts import render
from django.views.generic import ListView


from .models import Noticia

#Vasta Basada en funciones
def Home_Noticias(request):

	#ORM
	todas = Noticia.objects.all()

	contexto = {}

	contexto['noticias'] = todas
	contexto['fecha'] = '28-11-2023'

	return render(request, 'noticias/home_noticias.html', contexto)

#ACLARACION
'''
si bien en la vista armo un diccionario del tipo
{noticias: todas_noticias, fecha: '28-11-2023'}
en el template resivo variables separadas, una por cada clave, la cual contiene como valor
el valor de la clave
EJ, recibo 2 variales distintas, cuyo nombre es igual a la clave
noticias = todas_noticias
fecha = '28-11-2023'
'''

#VISTA BASADA EN CLASE
class Home_Noticias_clase(ListView):
	model = Noticia
	template_name = 'noticias/home_noticias.html'
	context_object_name = 'noticias'


#ORM
# CONSULTA PARA TRAER TODOS LOS DATOS
# select * from Noticia  SQL
# Noticia.objects.all()   ORM

#CONSuLTA PARA TRAER SOLO UN DATO (POR CLAVE)
# select * from Noticia where id = algo    SQL
# Noticia.objects.get(id = algo)		ORM

#CONSuLTA PARA TRAER SOLO Algunos datos (POR filtro)
# select * from Noticia where categororia = deportes
# Noticia.objects.filter(categoria = deportes)

proyecto/views.py
from django.shortcuts import render

def Home(request):

	return render(request,'home.html')

def Contacto(request):

	return render(request,'contacto.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>INFORMATORIO</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
	<h1 class="titulo">MENU</h1>
	<img src="{% static 'img/logo2.gif' %}" width="1200px">
	<ul>
		<li><a href="{% url 'inicio' %}">Home</a></li>
		<li><a href="{% url 'contacto' %}">Contacto</a>
		</li>
		<li><a href="{% url 'noticias:h_noticias' %}">NOTICIAS</a></li>
	</ul>

	{% block contenido %}

	{% endblock contenido %}

</body>
</html>

templates/contacto.html
{% extends 'base.html' %}


{% block contenido %}
	<h1>SOY CONTACTOS </h1>
{% endblock contenido %}

templates/home.html
{% extends 'base.html' %}


{% block contenido %}
	<h1>SOY EL HOME</h1>
{% endblock contenido %}

templates/noticias/homenoticias.html
{% extends 'base.html' %}


{% block contenido %}
	<h1>SOY HOME DE NOTICIAS</h1>

	{{fecha}}

	{% for n in noticias %}
		<div>
			<p><strong>TITULO:</strong>{{n.titulo}}</p>
			<p><strong>CONTENIDO:</strong>{{n.contenido}}</p>
		</div><hr><hr>
	{% endfor %}
{% endblock contenido %}